### ISSUE TITLE
Integrate upbound/build submodule

### ISSUE THREAD

**Issue by turkenh** [crossplane/provider-template#40]
We are using the [upbound/build](https://github.com/upbound/build) as a submodule for the majority of Crossplane providers and using consistent tooling provides a more streamlined experience. 

Integrating it here as well, would ease building providers from this repository especially regarding packaging and setting up CI pipelines.

**Comment by turkenh** [comment]
Hmm, looks like there is already an open PR for this: https://github.com/crossplane/provider-template/pull/19

/cc @negz

**Comment by negz** [comment]
Fixed by https://github.com/crossplane/provider-template/pull/19. :)
