### ISSUE TITLE
[Error] "PROJECT" file not found. 

### ISSUE THREAD

**Issue by Alt-Shivam** [crossplane/provider-template#54]
### What happened?

When I try to create a new API resource via this command.
```bash
kubebuilder create api --group network --version v1alpha1 --kind NetworkManager --resource=true --controller=false --namespaced=false
```
This throws an errors as follows.
```
failed to create API: unable to load configuration file: unable to load the configuration: unable to read "PROJECT" file: open PROJECT: no such file or directory
```

### How can we reproduce it?

Just click on **Use this template** button, and try to create an API resource via the command given above.

### What environment did it happen in?
Crossplane version: v1.9.0
Kubernetes version: v1.24.0
OS: Ubuntu 20LTS
Kernel: 5.13.0-52-generic

**Comment by dnlopes** [comment]
Having the same issue. How did you solve this @Alt-Shivam ?
