### ISSUE TITLE
"invalid memory address or nil pointer dereference" running example

### ISSUE THREAD

**Issue by pdettori** [crossplane/provider-template#7]
It seems this is caused by the "usage" in connector not being initialized: 
see https://github.com/crossplane/provider-template/blob/master/pkg/controller/mytype/mytype.go#L61

I get the error in https://github.com/crossplane/provider-template/blob/master/pkg/controller/mytype/mytype.go#L91

How should I initialize `usage` ?

**Comment by hasheddan** [comment]
@pdettori apologies for the delay here! Opening a fix for this now :)
