### ISSUE TITLE
Recommended Template for new provider development

### ISSUE THREAD

**Issue by karthik-murugan-hpe** [crossplane/provider-template#85]
The code I saw in TBS 18 https://youtu.be/rvQ8N0u3rkE is slightly different from this Provider template. 

Is this git repo, the recommended one to start a new Provider development or should we refer AWS/GCP repos?

**Comment by negz** [comment]
https://github.com/crossplane/upjet-provider-template is the place to start if you want to generate a Crossplane provider from an existing Terraform provider.

This repo is the place to start if you want to create a Crossplane provider "from scratch".
